/**:
  ros__parameters:
    common:
      img_topic: "/camera/image"
      lid_topic: "/livox/lidar"
      imu_topic: "/livox/imu"
      img_en: 1
      lidar_en: 1
      ros_driver_bug_fix: false # ROS driver bug fix.
      
    extrin_calib:      
      extrinsic_T: [ -0.011, -0.02329, 0.04412] 
      extrinsic_R: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
      # HD RMSE: 4mm
      Rcl: [  0.000772, -0.999992, -0.003882, 0.414344,  0.003853, -0.910112, 0.910120, -0.000906,  0.414344]
      Pcl: [ -0.000177, -0.092011, -0.035748]
      # SD RMSE: 5mm 
      # Rcl: [ -0.021654, -0.999727, -0.008741, 0.395164, -0.000528, -0.918611, 0.918355, -0.023346,  0.395067]
      # Pcl: [  0.009162, -0.079864, -0.026294]

    time_offset: 
      imu_time_offset: 0.0
      img_time_offset: 0.073        # measured base : 0.073 second. 
      exposure_time_init: 0.005     # Cam Exposure Time / 2 [sec] 5ms -> 0.005s

    preprocess:
      point_filter_num: 1
      filter_size_surf: 0.5
      lidar_type: 1 # Livox mid360 LiDAR
      scan_line: 4 
      blind: 0.5 #  blind area near LiDAR, [meter] {mid360 minimum: 0.1m physically}

    vio:
      min_iterations: 10
      outlier_threshold: 100 # 78 100 156 #100 200 500 700 infinite // photometric residual.
      img_point_cov: 1000 # 100 1000 // brightness measurement noise variance [intensty^2]; lower trusts the image more, higher trusts the LiDAR more
      patch_size: 8
      patch_pyrimid_level: 4
      normal_en: true
      raycast_en: true
      inverse_composition_en: false
      exposure_estimate_en: true
      inv_expo_cov: 0.1

    imu:
      imu_en: true
      imu_int_frame: 100
      acc_cov: 0.8 # 0.2 per sensor datasheet: 0.2, pcl5: 0.8, 0.5  https://github.com/pcl5/FAST-LIVO2/blob/main/config/mid360.yaml
      gyr_cov: 0.5 # 0.5 per sensor datasheet: 0.5
      b_acc_cov: 0.001 # 0.1 this value is unused anyway
      b_gyr_cov: 0.001 # 0.1 this value is unused anyway

    ## MID360 sepecific: 
    # Distance Random Error cov (1sigma) : =<2cm(@10m), =<3cm(@0.2m)
    # Angular Random Error cov (1sigma) : =<0.15° (w/o distance)
    # 200,000 points per second
    lio:
      min_iterations: 10       # number of convergence attempts
      dept_err: 0.03           # pcl : 0.02
      beam_err: 0.15           # pcl : 0.15
      min_eigen_value: 0.005   # lowered to accept more wall planes
      voxel_size: 0.5          # meter
      max_layer: 4             # higher voxel layers greatly increase computation
      max_points_num: 200      # increased per-voxel point limit
      layer_init_num: [5, 5, 5, 5, 5]  # lowered plane initialization threshold

    local_map:  
      map_sliding_en: false # map sliding. limits the maximum map size
      half_map_size: 100
      sliding_thresh: 5.0

    uav:
      imu_rate_odom: false
      gravity_align_en: true # true is correct https://github.com/hku-mars/FAST-LIVO2/issues/119

    publish:
      dense_map_en: true
      pub_effect_point_en: false
      pub_plane_en: true # publish voxels
      pub_scan_num: 1
      blind_rgb_points: 0.0

    evo:
      seq_name: "ALUX-office"
      pose_output_en: false

    pcd_save:
      pcd_save_en: true
      type: 0 # 0: World Frame, 1: Body Frame;
      colmap_output_en: false # need to set interval = -1 
      filter_size_pcd: 0.005 # point precision, unit: meter (5mm)
      interval: -1
      # how many LiDAR frames saved in each pcd file;
      # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

    image_save:
      img_save_en: false
      interval: 1

    # HD
    cam_model: Pinhole
    cam_width: 1280 # 1280
    cam_height: 720 # 720
    scale: 1.0
    cam_fx: 689.014802
    cam_fy: 686.491458
    cam_cx: 648.888053
    cam_cy: 353.230277
    cam_d0: -0.323225
    cam_d1: 0.113872
    cam_d2: -0.000056
    cam_d3: 0.000112
    
    # # Resolution:SD
    # cam_model: Pinhole
    # cam_width: 640
    # cam_height: 360
    # scale: 1.0
    # cam_fx: 344.902
    # cam_fy: 343.589
    # cam_cx: 324.879
    # cam_cy: 177.143
    # cam_d0: -0.334114
    # cam_d1: 0.125136
    # cam_d2: 0.000264
    # cam_d3: 0.00011

    # Resolution: FHD
    # cam_model: Pinhole
    # cam_width: 1920 
    # cam_height: 1080 
    # scale: 1.0
    # cam_fx: 1035.141685
    # cam_fy: 1030.924981
    # cam_cx: 971.634368
    # cam_cy: 539.160904
    # cam_d0: -0.330428
    # cam_d1: 0.121227
    # cam_d2: 0.000060
    # cam_d3: 0.000352

